/* This file was generated by SableCC (http://www.sablecc.org/). */

package min15.node;

import java.util.*;
import min15.analysis.*;

@SuppressWarnings("nls")
public final class AArgs extends PArgs
{
    private TEol _eol1_;
    private PArg _arg_;
    private final LinkedList<PAdditionalArg> _additionalArg_ = new LinkedList<PAdditionalArg>();
    private TEol _eol2_;

    public AArgs()
    {
        // Constructor
    }

    public AArgs(
        @SuppressWarnings("hiding") TEol _eol1_,
        @SuppressWarnings("hiding") PArg _arg_,
        @SuppressWarnings("hiding") List<?> _additionalArg_,
        @SuppressWarnings("hiding") TEol _eol2_)
    {
        // Constructor
        setEol1(_eol1_);

        setArg(_arg_);

        setAdditionalArg(_additionalArg_);

        setEol2(_eol2_);

    }

    @Override
    public Object clone()
    {
        return new AArgs(
            cloneNode(this._eol1_),
            cloneNode(this._arg_),
            cloneList(this._additionalArg_),
            cloneNode(this._eol2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgs(this);
    }

    public TEol getEol1()
    {
        return this._eol1_;
    }

    public void setEol1(TEol node)
    {
        if(this._eol1_ != null)
        {
            this._eol1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eol1_ = node;
    }

    public PArg getArg()
    {
        return this._arg_;
    }

    public void setArg(PArg node)
    {
        if(this._arg_ != null)
        {
            this._arg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arg_ = node;
    }

    public LinkedList<PAdditionalArg> getAdditionalArg()
    {
        return this._additionalArg_;
    }

    public void setAdditionalArg(List<?> list)
    {
        for(PAdditionalArg e : this._additionalArg_)
        {
            e.parent(null);
        }
        this._additionalArg_.clear();

        for(Object obj_e : list)
        {
            PAdditionalArg e = (PAdditionalArg) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._additionalArg_.add(e);
        }
    }

    public TEol getEol2()
    {
        return this._eol2_;
    }

    public void setEol2(TEol node)
    {
        if(this._eol2_ != null)
        {
            this._eol2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eol2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._eol1_)
            + toString(this._arg_)
            + toString(this._additionalArg_)
            + toString(this._eol2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._eol1_ == child)
        {
            this._eol1_ = null;
            return;
        }

        if(this._arg_ == child)
        {
            this._arg_ = null;
            return;
        }

        if(this._additionalArg_.remove(child))
        {
            return;
        }

        if(this._eol2_ == child)
        {
            this._eol2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._eol1_ == oldChild)
        {
            setEol1((TEol) newChild);
            return;
        }

        if(this._arg_ == oldChild)
        {
            setArg((PArg) newChild);
            return;
        }

        for(ListIterator<PAdditionalArg> i = this._additionalArg_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAdditionalArg) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._eol2_ == oldChild)
        {
            setEol2((TEol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
