/* This file was generated by SableCC (http://www.sablecc.org/). */

package min15.node;

import java.util.*;
import min15.analysis.*;

@SuppressWarnings("nls")
public final class AFile extends PFile
{
    private final LinkedList<PClassDef> _classDef_ = new LinkedList<PClassDef>();
    private PStmts _stmts_;

    public AFile()
    {
        // Constructor
    }

    public AFile(
        @SuppressWarnings("hiding") List<?> _classDef_,
        @SuppressWarnings("hiding") PStmts _stmts_)
    {
        // Constructor
        setClassDef(_classDef_);

        setStmts(_stmts_);

    }

    @Override
    public Object clone()
    {
        return new AFile(
            cloneList(this._classDef_),
            cloneNode(this._stmts_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFile(this);
    }

    public LinkedList<PClassDef> getClassDef()
    {
        return this._classDef_;
    }

    public void setClassDef(List<?> list)
    {
        for(PClassDef e : this._classDef_)
        {
            e.parent(null);
        }
        this._classDef_.clear();

        for(Object obj_e : list)
        {
            PClassDef e = (PClassDef) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._classDef_.add(e);
        }
    }

    public PStmts getStmts()
    {
        return this._stmts_;
    }

    public void setStmts(PStmts node)
    {
        if(this._stmts_ != null)
        {
            this._stmts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmts_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classDef_)
            + toString(this._stmts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classDef_.remove(child))
        {
            return;
        }

        if(this._stmts_ == child)
        {
            this._stmts_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PClassDef> i = this._classDef_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PClassDef) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._stmts_ == oldChild)
        {
            setStmts((PStmts) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
