/* This file was generated by SableCC (http://www.sablecc.org/). */

package min15.node;

import min15.analysis.*;

@SuppressWarnings("nls")
public final class ALteqOperator extends POperator implements IOperator
{
    private TLteq _lteq_;

    public ALteqOperator()
    {
        // Constructor
    }

    public ALteqOperator(
        @SuppressWarnings("hiding") TLteq _lteq_)
    {
        // Constructor
        setLteq(_lteq_);

    }

    @Override
    public Object clone()
    {
        return new ALteqOperator(
            cloneNode(this._lteq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALteqOperator(this);
    }

    public TLteq getLteq()
    {
        return this._lteq_;
    }

    public void setLteq(TLteq node)
    {
        if(this._lteq_ != null)
        {
            this._lteq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lteq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lteq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lteq_ == child)
        {
            this._lteq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lteq_ == oldChild)
        {
            setLteq((TLteq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    public Token GetOperator()
    {
        return getLteq();
    }
}
