/* This file was generated by SableCC (http://www.sablecc.org/). */

package min15.node;

import min15.analysis.*;

@SuppressWarnings("nls")
public final class ANegLeftUnaryExp extends PLeftUnaryExp
{
    private TMinus _minus_;
    private PLeftUnaryExp _leftUnaryExp_;

    public ANegLeftUnaryExp()
    {
        // Constructor
    }

    public ANegLeftUnaryExp(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PLeftUnaryExp _leftUnaryExp_)
    {
        // Constructor
        setMinus(_minus_);

        setLeftUnaryExp(_leftUnaryExp_);

    }

    @Override
    public Object clone()
    {
        return new ANegLeftUnaryExp(
            cloneNode(this._minus_),
            cloneNode(this._leftUnaryExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegLeftUnaryExp(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PLeftUnaryExp getLeftUnaryExp()
    {
        return this._leftUnaryExp_;
    }

    public void setLeftUnaryExp(PLeftUnaryExp node)
    {
        if(this._leftUnaryExp_ != null)
        {
            this._leftUnaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftUnaryExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._leftUnaryExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._leftUnaryExp_ == child)
        {
            this._leftUnaryExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._leftUnaryExp_ == oldChild)
        {
            setLeftUnaryExp((PLeftUnaryExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
