/* This file was generated by SableCC (http://www.sablecc.org/). */

package min15.node;

import java.util.*;
import min15.analysis.*;

@SuppressWarnings("nls")
public final class AParams extends PParams
{
    private TEol _eol1_;
    private PParam _param_;
    private final LinkedList<PAdditionalParam> _additionalParam_ = new LinkedList<PAdditionalParam>();
    private TEol _eol2_;

    public AParams()
    {
        // Constructor
    }

    public AParams(
        @SuppressWarnings("hiding") TEol _eol1_,
        @SuppressWarnings("hiding") PParam _param_,
        @SuppressWarnings("hiding") List<?> _additionalParam_,
        @SuppressWarnings("hiding") TEol _eol2_)
    {
        // Constructor
        setEol1(_eol1_);

        setParam(_param_);

        setAdditionalParam(_additionalParam_);

        setEol2(_eol2_);

    }

    @Override
    public Object clone()
    {
        return new AParams(
            cloneNode(this._eol1_),
            cloneNode(this._param_),
            cloneList(this._additionalParam_),
            cloneNode(this._eol2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParams(this);
    }

    public TEol getEol1()
    {
        return this._eol1_;
    }

    public void setEol1(TEol node)
    {
        if(this._eol1_ != null)
        {
            this._eol1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eol1_ = node;
    }

    public PParam getParam()
    {
        return this._param_;
    }

    public void setParam(PParam node)
    {
        if(this._param_ != null)
        {
            this._param_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._param_ = node;
    }

    public LinkedList<PAdditionalParam> getAdditionalParam()
    {
        return this._additionalParam_;
    }

    public void setAdditionalParam(List<?> list)
    {
        for(PAdditionalParam e : this._additionalParam_)
        {
            e.parent(null);
        }
        this._additionalParam_.clear();

        for(Object obj_e : list)
        {
            PAdditionalParam e = (PAdditionalParam) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._additionalParam_.add(e);
        }
    }

    public TEol getEol2()
    {
        return this._eol2_;
    }

    public void setEol2(TEol node)
    {
        if(this._eol2_ != null)
        {
            this._eol2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eol2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._eol1_)
            + toString(this._param_)
            + toString(this._additionalParam_)
            + toString(this._eol2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._eol1_ == child)
        {
            this._eol1_ = null;
            return;
        }

        if(this._param_ == child)
        {
            this._param_ = null;
            return;
        }

        if(this._additionalParam_.remove(child))
        {
            return;
        }

        if(this._eol2_ == child)
        {
            this._eol2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._eol1_ == oldChild)
        {
            setEol1((TEol) newChild);
            return;
        }

        if(this._param_ == oldChild)
        {
            setParam((PParam) newChild);
            return;
        }

        for(ListIterator<PAdditionalParam> i = this._additionalParam_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAdditionalParam) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._eol2_ == oldChild)
        {
            setEol2((TEol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
