/* This file was generated by SableCC (http://www.sablecc.org/). */

package min15.node;

import min15.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleFactor extends PFactor
{
    private PRightUnaryExp _rightUnaryExp_;

    public ASimpleFactor()
    {
        // Constructor
    }

    public ASimpleFactor(
        @SuppressWarnings("hiding") PRightUnaryExp _rightUnaryExp_)
    {
        // Constructor
        setRightUnaryExp(_rightUnaryExp_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleFactor(
            cloneNode(this._rightUnaryExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleFactor(this);
    }

    public PRightUnaryExp getRightUnaryExp()
    {
        return this._rightUnaryExp_;
    }

    public void setRightUnaryExp(PRightUnaryExp node)
    {
        if(this._rightUnaryExp_ != null)
        {
            this._rightUnaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightUnaryExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rightUnaryExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rightUnaryExp_ == child)
        {
            this._rightUnaryExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rightUnaryExp_ == oldChild)
        {
            setRightUnaryExp((PRightUnaryExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
