/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AFieldTerm extends PTerm
{
    private TFieldName _fieldName_;

    public AFieldTerm()
    {
        // Constructor
    }

    public AFieldTerm(
        @SuppressWarnings("hiding") TFieldName _fieldName_)
    {
        // Constructor
        setFieldName(_fieldName_);

    }

    @Override
    public Object clone()
    {
        return new AFieldTerm(
            cloneNode(this._fieldName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFieldTerm(this);
    }

    public TFieldName getFieldName()
    {
        return this._fieldName_;
    }

    public void setFieldName(TFieldName node)
    {
        if(this._fieldName_ != null)
        {
            this._fieldName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fieldName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fieldName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fieldName_ == child)
        {
            this._fieldName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fieldName_ == oldChild)
        {
            setFieldName((TFieldName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
