/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIsaRightUnaryExp extends PRightUnaryExp
{
    private PRightUnaryExp _rightUnaryExp_;
    private TIsa _isa_;
    private TClassName _className_;

    public AIsaRightUnaryExp()
    {
        // Constructor
    }

    public AIsaRightUnaryExp(
        @SuppressWarnings("hiding") PRightUnaryExp _rightUnaryExp_,
        @SuppressWarnings("hiding") TIsa _isa_,
        @SuppressWarnings("hiding") TClassName _className_)
    {
        // Constructor
        setRightUnaryExp(_rightUnaryExp_);

        setIsa(_isa_);

        setClassName(_className_);

    }

    @Override
    public Object clone()
    {
        return new AIsaRightUnaryExp(
            cloneNode(this._rightUnaryExp_),
            cloneNode(this._isa_),
            cloneNode(this._className_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIsaRightUnaryExp(this);
    }

    public PRightUnaryExp getRightUnaryExp()
    {
        return this._rightUnaryExp_;
    }

    public void setRightUnaryExp(PRightUnaryExp node)
    {
        if(this._rightUnaryExp_ != null)
        {
            this._rightUnaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightUnaryExp_ = node;
    }

    public TIsa getIsa()
    {
        return this._isa_;
    }

    public void setIsa(TIsa node)
    {
        if(this._isa_ != null)
        {
            this._isa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._isa_ = node;
    }

    public TClassName getClassName()
    {
        return this._className_;
    }

    public void setClassName(TClassName node)
    {
        if(this._className_ != null)
        {
            this._className_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._className_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rightUnaryExp_)
            + toString(this._isa_)
            + toString(this._className_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rightUnaryExp_ == child)
        {
            this._rightUnaryExp_ = null;
            return;
        }

        if(this._isa_ == child)
        {
            this._isa_ = null;
            return;
        }

        if(this._className_ == child)
        {
            this._className_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rightUnaryExp_ == oldChild)
        {
            setRightUnaryExp((PRightUnaryExp) newChild);
            return;
        }

        if(this._isa_ == oldChild)
        {
            setIsa((TIsa) newChild);
            return;
        }

        if(this._className_ == oldChild)
        {
            setClassName((TClassName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
