/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AModFactor extends PFactor
{
    private PFactor _factor_;
    private TPercent _percent_;
    private TEol _eol_;
    private PLeftUnaryExp _leftUnaryExp_;

    public AModFactor()
    {
        // Constructor
    }

    public AModFactor(
        @SuppressWarnings("hiding") PFactor _factor_,
        @SuppressWarnings("hiding") TPercent _percent_,
        @SuppressWarnings("hiding") TEol _eol_,
        @SuppressWarnings("hiding") PLeftUnaryExp _leftUnaryExp_)
    {
        // Constructor
        setFactor(_factor_);

        setPercent(_percent_);

        setEol(_eol_);

        setLeftUnaryExp(_leftUnaryExp_);

    }

    @Override
    public Object clone()
    {
        return new AModFactor(
            cloneNode(this._factor_),
            cloneNode(this._percent_),
            cloneNode(this._eol_),
            cloneNode(this._leftUnaryExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModFactor(this);
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    public TPercent getPercent()
    {
        return this._percent_;
    }

    public void setPercent(TPercent node)
    {
        if(this._percent_ != null)
        {
            this._percent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._percent_ = node;
    }

    public TEol getEol()
    {
        return this._eol_;
    }

    public void setEol(TEol node)
    {
        if(this._eol_ != null)
        {
            this._eol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eol_ = node;
    }

    public PLeftUnaryExp getLeftUnaryExp()
    {
        return this._leftUnaryExp_;
    }

    public void setLeftUnaryExp(PLeftUnaryExp node)
    {
        if(this._leftUnaryExp_ != null)
        {
            this._leftUnaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftUnaryExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factor_)
            + toString(this._percent_)
            + toString(this._eol_)
            + toString(this._leftUnaryExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        if(this._percent_ == child)
        {
            this._percent_ = null;
            return;
        }

        if(this._eol_ == child)
        {
            this._eol_ = null;
            return;
        }

        if(this._leftUnaryExp_ == child)
        {
            this._leftUnaryExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        if(this._percent_ == oldChild)
        {
            setPercent((TPercent) newChild);
            return;
        }

        if(this._eol_ == oldChild)
        {
            setEol((TEol) newChild);
            return;
        }

        if(this._leftUnaryExp_ == oldChild)
        {
            setLeftUnaryExp((PLeftUnaryExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
