/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotLeftUnaryExp extends PLeftUnaryExp
{
    private TNot _not_;
    private PLeftUnaryExp _leftUnaryExp_;

    public ANotLeftUnaryExp()
    {
        // Constructor
    }

    public ANotLeftUnaryExp(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PLeftUnaryExp _leftUnaryExp_)
    {
        // Constructor
        setNot(_not_);

        setLeftUnaryExp(_leftUnaryExp_);

    }

    @Override
    public Object clone()
    {
        return new ANotLeftUnaryExp(
            cloneNode(this._not_),
            cloneNode(this._leftUnaryExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotLeftUnaryExp(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PLeftUnaryExp getLeftUnaryExp()
    {
        return this._leftUnaryExp_;
    }

    public void setLeftUnaryExp(PLeftUnaryExp node)
    {
        if(this._leftUnaryExp_ != null)
        {
            this._leftUnaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftUnaryExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._leftUnaryExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._leftUnaryExp_ == child)
        {
            this._leftUnaryExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._leftUnaryExp_ == oldChild)
        {
            setLeftUnaryExp((PLeftUnaryExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
