/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASelfCallTerm extends PTerm
{
    private PSelfCall _selfCall_;

    public ASelfCallTerm()
    {
        // Constructor
    }

    public ASelfCallTerm(
        @SuppressWarnings("hiding") PSelfCall _selfCall_)
    {
        // Constructor
        setSelfCall(_selfCall_);

    }

    @Override
    public Object clone()
    {
        return new ASelfCallTerm(
            cloneNode(this._selfCall_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASelfCallTerm(this);
    }

    public PSelfCall getSelfCall()
    {
        return this._selfCall_;
    }

    public void setSelfCall(PSelfCall node)
    {
        if(this._selfCall_ != null)
        {
            this._selfCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._selfCall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._selfCall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._selfCall_ == child)
        {
            this._selfCall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._selfCall_ == oldChild)
        {
            setSelfCall((PSelfCall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
