/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASimpleFactor extends PFactor
{
    private PLeftUnaryExp _leftUnaryExp_;

    public ASimpleFactor()
    {
        // Constructor
    }

    public ASimpleFactor(
        @SuppressWarnings("hiding") PLeftUnaryExp _leftUnaryExp_)
    {
        // Constructor
        setLeftUnaryExp(_leftUnaryExp_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleFactor(
            cloneNode(this._leftUnaryExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleFactor(this);
    }

    public PLeftUnaryExp getLeftUnaryExp()
    {
        return this._leftUnaryExp_;
    }

    public void setLeftUnaryExp(PLeftUnaryExp node)
    {
        if(this._leftUnaryExp_ != null)
        {
            this._leftUnaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftUnaryExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._leftUnaryExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._leftUnaryExp_ == child)
        {
            this._leftUnaryExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._leftUnaryExp_ == oldChild)
        {
            setLeftUnaryExp((PLeftUnaryExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
