/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TIntern extends Token
{
    public TIntern()
    {
        super.setText("intern");
    }

    public TIntern(int line, int pos)
    {
        super.setText("intern");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIntern(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIntern(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIntern text.");
    }
}
